### ISSUE TITLE
TopGames returning NULL

### ISSUE THREAD

**Issue by RickTheHat** [michidk/TwitchCSharp#2]
Is anyone else having issues calling "Top Games"? Yesterday I was getting data back all the time while in development but today when I went back to testing, I get null every time. I wonder if Twitch banned my IP? Is there anyway to get error codes? I'm using the read only client so no access needed.

**Comment by michidk** [comment]
Thats strage... There should be a .Message or .Error Methode.. try writing the result into console.
You could also try to make the request with https://www.hurl.it

**Comment by RickTheHat** [comment]
it was me, not you ... doh
